# Generated by Django 5.1.2 on 2024-11-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.DecimalField(decimal_places=1, max_digits=50),
        ),
    ]
