# Generated by Django 5.1.2 on 2024-11-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_alter_vehiculo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='condicion_precio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
