# Generated by Django 5.1.2 on 2024-11-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_vehiculo_condicion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
