# Generated by Django 5.1.2 on 2024-11-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_alter_vehiculo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='precio',
            field=models.DecimalField(decimal_places=1, max_digits=50),
        ),
    ]
